name: Greeting on variable day

on:
  push:
    branches: [main]

env:
    DAY_OF_WEEK: Monday

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: checkout repo
         uses: actions/checkout@v4

       - name: name of branch
         run: echo $(git branch --show-current) && du -skh --exclude=".git"