name: mirroring

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:brice825KA/Chocolatine.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY  }}

  to_code_commit:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - uses: pixta-dev/repository-mirroring-action@v1
         with:
           target_repo_url: ssh://git@github.com:brice825KA/Copy_of_Chocolatine.git
           ssh_private_key: ${{ secrets.ODECOMMIT_SSH_PRIVATE_KEY }}