name: date commit
run-name: ${{ github.actor }} is learning Github Actions

on:
    push:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest:
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: display date
        run: date